build:
  number: 0
  skip: True # [osx]

package:
  name: sickle
  version: "0.5"

source:
  url: https://pypi.python.org/packages/source/S/Sickle/Sickle-0.5.tar.gz
  md5: 9c93e7f3e0db98ab1a18107dfa096082

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - requests >=1.1.0
    - lxml >=3.2.3

  run:
    - python
    - requests >=1.1.0
    - lxml >=3.2.3

test:
  # Python imports
  imports:
    - sickle

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock >=1.0.1
    - nose >=1.0
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mloesch/sickle
  license: BSD License
  summary: 'A lightweight OAI client library for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
