package:
  name: taxtastic
  version: "0.5.4"

source:
  fn: taxtastic-0.5.4.tar.gz
  url: https://pypi.python.org/packages/source/t/taxtastic/taxtastic-0.5.4.tar.gz
  md5: 42e82d6370fad3da154c94c9f05000c8

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - sqlalchemy >=0.7
    - decorator
    - biopython
    - xlrd

  run:
    - python
    - sqlalchemy >=0.7
    - decorator
    - biopython
    - xlrd

test:
  # Python imports
  imports:
    - taxtastic
    - taxtastic.scripts
    - taxtastic.subcommands


about:
  home: https://github.com/fhcrc/taxtastic
  license: GNU General Public License (GPL)
  summary: 'Tools for taxonomic naming and annotation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
