build:
  number: 0
  skip: True # [osx]

package:
  name: pypore
  version: "0.0.5.dev20160304220337"

source:
  fn: pypore-0.0.5.dev20160304220337.tar.gz
  url: https://pypi.python.org/packages/source/p/pypore/pypore-0.0.5.dev20160304220337.tar.gz
  md5: 173ebb6a8ca721630468ffd5940029fd

requirements:
  host:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - pypore
    - pypore.filetypes
    - pypore.filetypes.tests
    - pypore.i_o
    - pypore.i_o.tests
    - pypore.sampledata
    - pypore.sampledata.tests
    - pypore.strategies
    - pypore.strategies.tests
    - pypore.tests
    - pyporegui
    - pyporegui.graphicsItems
    - pyporegui.graphicsItems.tests
    - pyporegui.tests
    - pyporegui.widgets
    - pyporegui.widgets.tests

about:
  home: http://parkin.github.io/pypore/
  license: Apache License, Version 2.0
  summary: 'Pythonic/Cythonic Nanopore Translocation Analysis'

