{% set version = "3.1.0" %}

package:
  name: kmc
  version: {{ version }}

source:
  # Building kmc_tools requires C++14 features which bioconda does not yet support.
  # Therefore, we fetch statically-linked binaries.
  fn: KMC{{ version }}.linux.tar.gz  # [linux]
  url: https://github.com/refresh-bio/KMC/releases/download/v{{ version }}/KMC{{ version }}.linux.tar.gz  # [linux]
  sha256: 7abe221aad70daf01893de017a287c342fd29ba24e69b2dac6502d321cf170cb

build:
  number: 0

test:
  commands:
    - kmc 2>&1 | grep "K-Mer Counter (KMC) ver. {{ version }}" > /dev/null
    - kmc_dump 2>&1 | grep "KMC dump ver. {{ version }}" > /dev/null
    - kmc_tools 2>&1 | grep "kmc_tools ver." > /dev/null

about:
  home: http://sun.aei.polsl.pl/kmc/
  license: GPLv2
  summary: K-mer Counter is a utility designed for counting k-mers (sequences of consecutive k symbols) in a set of reads from genome sequencing projects.

extra:
  
