{% set name = "confindr" %}
{% set version = "0.3.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fb0489381739c86ca0939fa93aee5d61ad4fa40eeeda760b7a9c0d9297f6d8e0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True # [py27]

requirements:
  build:
    - python
    - setuptools
    - biopython
    - pysam
    - pytest
    - bbmap
    - jellyfish
    - blast
    - mash >=2
    - samtools
    - pip
  run:
    - python
    - biopython
    - pysam
    - pytest
    - bbmap
    - jellyfish
    - blast
    - mash >=2
    - samtools

test:
  imports:
    - confindr
  commands:
    - confindr.py --version

about:
  home: https://github.com/lowandrew/ConFindr
  license: MIT
  license_family: MIT
  summary: 'Detect intra- and inter-species bacterial contamination in NGS reads'
  doc_url: 'https://lowandrew.github.io/ConFindr/'
  dev_url: 'https://github.com/lowandrew/ConFindr'

extra:
  recipe-maintainers: 'Andrew Low'
