package:
  name: flowcraft
  version: "1.2.0"

source:
  fn: flowcraft-1.2.0.tar.gz
  url: https://files.pythonhosted.org/packages/97/8f/09f3d8ac8205154f4d3e29535861fc87469e662c81650b4019f9917b4f4b/flowcraft-1.2.0.tar.gz
  md5: 4b07d38cd4d33b2dea79ce0e3079c8f7

build:
  skip: True # [py27]
  entry_points:
    - flowcraft = flowcraft.flowcraft:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pympler
    - python-dateutil
    - argparse
    - jinja2
    - requests

  run:
    - python
    - pympler
    - python-dateutil
    - argparse
    - jinja2
    - requests
    - nextflow >=0.27

test:
  # Python imports
  imports:
    - flowcraft
    - flowcraft.generator
    - flowcraft.generator.components
    - flowcraft.templates

  commands:
    - flowcraft --help

about:
  home: https://github.com/assemblerflow/flowcraft
  license: GPL3
  summary: 'A Nextflow pipeline assembler for genomics. Pick your modules. Assemble them. Run the pipeline.'
  license_family: GPL3
  license_file: LICENSE
  summary: A Nextflow pipeline assembler for genomics. Pick your modules. Assemble them. Run the pipeline.
  doc_url:  http://assemblerflow.readthedocs.io/en/latest/
  dev_url: http://assemblerflow.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
      - odiogosilva

